# fly.toml app configuration file generated for sapphic-moe on 2024-12-25T01:01:51+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sapphic-moe'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
