# fly.toml app configuration file for sapphic
app = "sapphic"
primary_region = "fra"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_headers]]
# Allow CORS headers for Giscus requests
for = "https://sapphic.moe"
[services.http_headers.response]
Access-Control-Allow-Origin = "https://giscus.app"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "*"
Access-Control-Expose-Headers = "*"
